### ISSUE TITLE
Qt Example as starter

### ISSUE THREAD

**Issue by wallerka77** [Tereius/libONVIF#11]
Hi Björn,
I don't know if I have to open an issue for this...
I am very happy that I could compile and install your lib libONVIF on my Raspberry Pi! Great!

It would be very helpful to have a runnable example in Qt or cpp available as a starter.

Functions:
-Find camera on local network
-display stream in a GUI, preferably in a Qt widget
-zoom setting

I have not found anything on the net.
As I said, I don't know if this is the right way here in this issue.
Nevertheless I would like to thank you for your great support!!!

**Comment by Tereius** [comment]
Hi,
Some years ago I started a Qt ONVIF app that I never finished. I made this repo public some minutes ago: https://github.com/Tereius/ONVIFMonitor. I hope this gets you started with libONVIF.
Furthermore the libONVIF comes with a small application (named onvifinfo) that does some device-discovery, inspection. You may want to look at the [source code](https://github.com/Tereius/libONVIF/blob/master/src/main.cpp).

**Comment by wallerka77** [comment]
Hi Björn,

i just discovered onvifinfo and indeed it found 3 cameras in my network, yeah!!!!
I am so happy!!!

i didn't think i would get this far but with your help .... Thanks!

What files are needed for onvifinfo?
Maybe I can learn something from it.

Sometimes I am a little confused because there are so many files and, as you know, we had problems with the build directory before.

I tried to assimilate a main.cpp source code into a Qt widget project.
Unfortunately there were a lot of errors because I probably didn't implement the libONVIF libs into the Qt pro file correctly.

Now I'll try to make your example work ...

Thanks
Walter

**Comment by Tereius** [comment]
Have a look at [CMakeLists.txt:448](https://github.com/Tereius/libONVIF/blob/121617358aedf817225da31ae0e011d860388eec/src/CMakeLists.txt#L448). There you see what files are needed for onvifinfo and what libONVIF dependencies are needed. You should have a look at ONVIFMonitor; especially the two files [Device.h](https://github.com/Tereius/ONVIFMonitor/blob/master/src/Device.h) and [Device.cpp](https://github.com/Tereius/ONVIFMonitor/blob/master/src/Device.cpp).
