### ISSUE TITLE
No IPv4Address found while executing GetNTP 

### ISSUE THREAD

**Issue by dix75** [Tereius/libONVIF#13]
Hello!

IPv4Address is empty (IPv4Address is nullptr) when I try to use GetNTP.
soap responce
`<SOAP-ENV:Body><tds:GetNTPResponse><tds:NTPInformation><tt:FromDHCP>false</tt:FromDHCP><tt:NTPManual><tt:Type>IPv4</tt:Type><tt:IPv4Address>172.17.4.51</tt:IPv4Address></tt:NTPManual></tds:NTPInformation></tds:GetNTPResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>`

Code
`      auto builder = SoapCtx::Builder();
        auto ctx = builder.EnableOMode(SOAP_XML_INDENT)
                .SetConnectTimeout(1000)
                .Build();

            ctx->EnablePrintRawSoap();

            OnvifDeviceClient onf(dev.onvifAddress(), ctx);
            onf.SetAuth(dev.login(), dev.pass(), AUTO);

            Request<_tds__GetNTP> req;
            auto const res = onf.GetNTP(req);
            if(res)
                auto ntp = res.GetResultObject()->NTPInformation;
                qDebug() << ntp->FromDHCP;
                qDebug() << ntp->Extension;
                for(auto h: ntp->NTPFromDHCP) {
                    qDebug() << "dhcp";
                    qDebug() << (int)h->Type;
                    qDebug() << h->DNSname;
                    qDebug() << h->IPv4Address;
                    qDebug() << h->IPv6Address;
                }
                for(auto h: ntp->NTPManual) {
                    qDebug() << "manual";
                    qDebug() << (int)h->Type;
                    qDebug() << h->DNSname;
                    qDebug() << h->Extension;
                    qDebug() << h->IPv4Address;    // is NULL
                    qDebug() << h->IPv6Address;
                }`

**Comment by Tereius** [comment]
Hi,

you are right. The IP address doesn't get serialized. It's a gsoap bug. Please switch to the **dev** branch with a more recent gsoap version.
