### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by selmehtar** [Tereius/libONVIF#3]
Hello, I am implementing a test project including the ONVIF library but I get an error when calling the GetProfiles() function: 'SOAP_SSL_ERROR'. 
Any idea about how could I solve it?

**Comment by Tereius** [comment]
I must admit I never tested the openssl integration.
At first make sure that the CMake variables "OpenSSL_cryptro_PATH", "OpenSSL_include_DIR", "OpenSSL_ssl_PATH" are set correctly. After that you have to enable ssl support programmatically by calling [SoapCtx::EnableSsl()](https://github.com/Tereius/libONVIF/blob/02d9b5fc3ab29f9e7b3e64047251286b87b891b1/src/SoapCtx.h#L85). I would use the [SoapCtx::Builder](https://github.com/Tereius/libONVIF/blob/02d9b5fc3ab29f9e7b3e64047251286b87b891b1/src/SoapCtx.h#L134) to create a ssl enabled soap ctx like so:

```
auto ctxBuilder = SoapCtx::Builder();
ctxBuilder.EnableSsl();
auto deviceClient = new OnvifDeviceClient(QUrl("https://[...]"), ctxBuilder.Build());
```

**Comment by selmehtar** [comment]
It worked, thank you!
