### ISSUE TITLE
Cmake compiler error : soapC.cpp.obj 'File too big'

### ISSUE THREAD

**Issue by bknhatice** [Tereius/libONVIF#5]
Hi,

cd <src_path> after cmake commend. But error: 
Fatal error: can't write 139 bytes to section .text of CMakeFiles\onvifcommon.dir\generated\soapC.cpp.obj: 'File too big'
CMakeFiles\onvifcommon.dir\generated\soapC.cpp.obj: too many sections 

can you help me ? Thank you.

**Comment by Tereius** [comment]
Hi,

it would be very helpful if you would provide more details concerning the compiler, os (32 bit or 64 bit), architecture, a complete log file. Remember you can change the compiler/linker flags by setting: CMAKE_CXX_FLAGS, CMAKE_SHARED_LINKER_FLAGS. Perhaps you have to experiment with those flags [as suggested here](https://digitalkarabela.com/mingw-w64-how-to-fix-file-too-big-too-many-sections/).
