### ISSUE TITLE
generated folder

### ISSUE THREAD

**Issue by p3im4n** [Tereius/libONVIF#7]
hi Mr @Tereius 
how do you generate all the file in generated folder?

**Comment by Tereius** [comment]
Hi,
set following CMake cache variables "ENABLE_CODESYNTHESIS", "Gsoap_import_DIR", "Gsoap_soapcpp2_PATH", "Gsoap_wsdl2h_PATH": `cmake -G "Unix Makefiles" -DENABLE_CODESYNTHESIS="ON" -DGsoap_import_DIR="<import_path>" -DGsoap_soapcpp2_PATH="<soapcpp2_executable_path>" -DGsoap_wsdl2h_PATH="<wdsl2h_executable_path>"` and run the target "Synthesis": `cmake --build ./ --target Synthesis`.
