### ISSUE TITLE
Install libONVIF on Raspberry Pi

### ISSUE THREAD

**Issue by wallerka77** [Tereius/libONVIF#8]
Hello,
I am a complete beginner in ONVIF. I am trying to install libONVIF on my 
Raspberry Pi 4B 8GB and 32Bit OS.

Unfortunately I fail at the point:
conan install ./ -o build_type=Debug --build missing

with the error message:
conan install ./ -o build_type=Debug --build missing
Configuration:
[settings]
arch=armv7
arch_build=armv7
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=8
os=Linux
os_build=Linux
[options]
build_type=Debug
[build_requires]
[env]

ERROR: /home/pi/software/ONVIF/libONVIF-master/conanfile.py: option 'build_type' doesn't exist
Possible options are ['shared', 'openssl']

Can anyone tell me what to do here?
Thanks a lot
Walter

**Comment by Tereius** [comment]
My bad. I have made a mistake in the INSTALL document: ```build_type``` only belongs in settings. The correct command is: ```conan install ./ -s build_type=Debug --build missing```.

**Comment by wallerka77** [comment]
Hi Tereius,

thank you for the quick reply!
Your correction of the command worked. Great!
My Pi has slaved a lot, but some time later there was a new error:

chmod a+x util/shlib_wrap.sh
make[1]: Leaving directory '/home/pi/.conan/data/OpenSSL/1.1.1b/tereius/stable/build/61498798ee9fabc722119341f6ebd123b6a101ba/openssl-OpenSSL_1_1_1b'
OpenSSL/1.1.1b@tereius/stable:  
OpenSSL/1.1.1b@tereius/stable: Package '61498798ee9fabc722119341f6ebd123b6a101ba' built
OpenSSL/1.1.1b@tereius/stable: Build folder /home/pi/.conan/data/OpenSSL/1.1.1b/tereius/stable/build/61498798ee9fabc722119341f6ebd123b6a101ba
OpenSSL/1.1.1b@tereius/stable: Generated conaninfo.txt
OpenSSL/1.1.1b@tereius/stable: Generated conanbuildinfo.txt
OpenSSL/1.1.1b@tereius/stable: Generating the package
OpenSSL/1.1.1b@tereius/stable: Package folder /home/pi/.conan/data/OpenSSL/1.1.1b/tereius/stable/package/61498798ee9fabc722119341f6ebd123b6a101ba
OpenSSL/1.1.1b@tereius/stable: Calling package()
OpenSSL/1.1.1b@tereius/stable package(): Packaged 104 '.h' files
OpenSSL/1.1.1b@tereius/stable package(): Packaged 1 file: LICENSE
OpenSSL/1.1.1b@tereius/stable package(): Packaged 2 '.so' files: libcrypto.so, libssl.so
OpenSSL/1.1.1b@tereius/stable package(): Packaged 1 '.c' file: applink.c
OpenSSL/1.1.1b@tereius/stable package(): Packaged 2 '.H' files: __DECC_INCLUDE_PROLOGUE.H, __DECC_INCLUDE_EPILOGUE.H
OpenSSL/1.1.1b@tereius/stable package(): Packaged 2 '.1' files: libcrypto.so.1.1, libssl.so.1.1
OpenSSL/1.1.1b@tereius/stable: Package '61498798ee9fabc722119341f6ebd123b6a101ba' created
OpenSSL/1.1.1b@tereius/stable: Created package revision 6c19743e12126c4aca538e15550abefc
Downloading conan_sources.tgz completed [1322.98k]                                       
Decompressing conan_sources.tgz completed [0.00k]                                        
Qt/5.12.4@tereius/stable: Configuring sources in /home/pi/.conan/data/Qt/5.12.4/tereius/stable/source
Downloading qt-everywhere-src-5.12.4.tar.xz completed [496052.93k]                              

ERROR: Qt/5.12.4@tereius/stable: Error in source() method, line 150
	tools.get("%s.tar.xz" % url)
	ConanException: XZ format not supported in Python 2. Use Python 3 instead
pi@raspberrypi:~/software/ONVIF/libONVIF-master $ 

So, what to do now?
I have no ddea...

Alll the best...
Walter

**Comment by wallerka77** [comment]
Hi,

one question: Is there an example (maybe with Qt )for your libONVIF where e.g. the stream of the camera 

is shown in a widget and you can adjust the zoom of the camera?

That would be great!  <https://github.com/notifications/beacon/ASFPS6SXN6SCIDIHKW747LTSVO2CXA5CNFSM4VBJD3BKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFSNCC7Y.gif> 

 

Thanks

Walter
