### ISSUE TITLE
ERROR:  cmake_minimum_required(VERSION 3.13)

### ISSUE THREAD

**Issue by wallerka77** [Tereius/libONVIF#9]
Hello,

unfortunately another fail occured:

pi@raspberrypi:~/software/ONVIF/libONVIF-master/build $ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug /home/pi/software/ONVIF/libONVIF-master/src
CMake Error: File /home/pi/software/ONVIF/libONVIF-master/src/CMake/libONVIFConfig.cmake.in does not exist.
CMake Error at /usr/share/cmake-3.13/Modules/CMakePackageConfigHelpers.cmake:316 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:482 (configure_package_config_file)

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/pi/software/ONVIF/libONVIF-master/build/CMakeFiles/CMakeOutput.log".

In CMakeLists.txt at top of the file you can find:
cmake_minimum_required(VERSION 2.8.12)

Note:
Python on my Raspberry Pi:

pi@raspberrypi:~ $ whereis python
python: /usr/bin/python3.7 /usr/bin/python /usr/bin/python3.7m /usr/bin/python3.7m-config /usr/bin/python2.7 /usr/bin/python2.7-config /usr/bin/python3.7-config /usr/lib/python3.7 /usr/lib/python2.7 /etc/python3.7 /etc/python /etc/python2.7 /usr/local/lib/python3.7 /usr/local/lib/python2.7 /usr/include/python3.7 /usr/include/python3.7m /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz
[CMakeOutput.log](https://github.com/Tereius/libONVIF/files/5719227/CMakeOutput.log)

**Comment by Tereius** [comment]
You picked the wrong CMakeLists.txt file. Don't use the one in the src directory. Use the one in the root directory of the repo. The command should be: ```cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug /home/pi/software/ONVIF/libONVIF-master```
